site_name: ChromCompare Documentation
repo_url: https://github.com/sof202/ChromCompare
site_description: "Documentation for ChromCompare"
site_author: "Sam Fletcher"
copyright: "© 2024, Sam Fletcher"
theme:
  logo: logo.svg
  favicon: logo.svg
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green


